name: Static code analysis

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    container: doncsenko13/test_image:latest
    steps:
      - uses: actions/checkout@v2
      - name: run
        run: cppcheck *.cpp
