name: Static code analysis

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install cppcheck
        run: sudo apt-get install cppcheck
      - name: run
        run: cppcheck *.cpp